import json
from cove_rag.cove_agent import CoveAgent
from cove_rag.rag_chat_agent import ChatAgent
from demo_data.hallucinated_answer import HALLUCINATED_ANSWER
from cove_rag.prompts import (
    VERIFICATION_QUESTION_INSTRUCTIONS, 
    VERIFICATION_ANSWER_INSTRUCTIONS, 
    REGENERATION_INSTRUCTIONS)

DUMMY_REVIEWS_DATA_PATH = "demo_data/dummy_reviews.json" 

if __name__ == "__main__":
    cove_agent = CoveAgent()
    chat_agent = ChatAgent()

    # Step 0) We assume a summary is already generated by the ChatAgent and it is stored in HALLUCINATED_ANSWER

    # Step 1) The CoveAgent will generate verification questions
    cove_verification_questions = cove_agent.generate_response(system_instruction=VERIFICATION_QUESTION_INSTRUCTIONS,
                                                 query=f"Summary: {HALLUCINATED_ANSWER}")

    # Step 2) The ChatAgent will generate verification answers
    with open(DUMMY_REVIEWS_DATA_PATH, "r") as f:
        reviews_data = json.load(f)
    
    verification_answer_instruction_prompt = f"Reviews: {reviews_data}\n{VERIFICATION_ANSWER_INSTRUCTIONS}"
    chat_verification_question_and_answers = chat_agent.generate_response(system_instruction=verification_answer_instruction_prompt,
                                                             query=f"Questions: {cove_verification_questions}")

    # Step 3) The ChatAgent will generate a new summary based on the verification answers
    regeneration_instruction_prompt = f"retrieved_reviews: {reviews_data}\n\
        initial_summary: {HALLUCINATED_ANSWER}\n\
            verification_questions_and_answers: {chat_verification_question_and_answers}"
    final_summary = chat_agent.generate_response(system_instruction=REGENERATION_INSTRUCTIONS,
                                                 query=f"{regeneration_instruction_prompt}")

    # Save all the outputs into a single file
    output_path = "demo_data/outputs.txt"
    with open(output_path, "w") as f:
        f.write(f"Step 0) ChatAgent - Hallucinated Answer:\n{HALLUCINATED_ANSWER}\n")
        f.write(f"\nStep 1) CoveAgent - Verification Questions:\n{cove_verification_questions}\n")
        f.write(f"\nStep 2) ChatAgent - Verification Question and Answers:\n{chat_verification_question_and_answers}\n")
        f.write(f"\nStep 3) ChatAgent - Final Summary:\n{final_summary}\n")

    print(f"The system outputs are saved in {output_path}")