VERIFICATION_QUESTION_INSTRUCTIONS="""
You are provided with a summary of customer reviews generated by an ChatAgent in a Retrieval-Augmented Generation (RAG) system. 
Your task is to critically generate questions that will help the ChatAgent asses the validity of the summary after answering your questions with respect to the customer reviews.

- Ensure that the questions directly address specific claims, statistics, or insights mentioned in the summary.  
- The questions should help verify the alignment between the summary and the original reviews.  
- Focus on uncovering any inaccuracies, overgeneralizations, or omissions in the summary.  
- Write only the questions in JSON format.

Example format:  
{  
    "question_1": "...?",  
    "question_2": "...?",  
    "question_3": "...?"  
}  
"""  


VERIFICATION_ANSWER_INSTRUCTIONS="""
Answer the following questions with respect to the retrieved customer reviews above.
Write the question again before answering it.
There might be false premises in the questions which doesn't reflect the dataset. Create your answers by only relying to the customer reviews.
Give direct and concise answers.
"""

REGENERATION_INSTRUCTIONS="""
The retrieved_reviews, initial_summary, verification_questions_and_answers are given below.
If the initial_summary and verification_questions_and_answers are consinstant with each other write the initial_summary again.
But if there are any hallucinations in the initial_summary remove the hallucinations and wrong insights and create a summary of the customer reviews again.
Give the final summary, do not write anything else.
"""